name: Teams Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Teams Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "${{ github.event.pull_request.title }}"
          summary: "New Pull Request Created"
          theme-color: "008080"
          text: "Created by @${{ github.event.pull_request.user.login }}. [Link to PR](${{ github.event.pull_request.html_url }})"
