name: Telegram Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "New Pull Request Created: ${{ github.event.pull_request.title }} by @${{ github.event.pull_request.user.login }}. Link: ${{ github.event.pull_request.html_url }}"
